/**
 * SISMP — Permission Matrix
 * Maps roles to their allowed actions and route access.
 * Components use RoleGate to conditionally render — never render-then-disable.
 */

import { ROLES, type Role } from './roles';

export const PERMISSIONS = {
  // Registration
  REGISTER: 'register',
  VIEW_OWN_REGISTRATION: 'view_own_registration',
  VIEW_ALL_REGISTRATIONS: 'view_all_registrations',
  APPROVE_REGISTRATION: 'approve_registration',
  REJECT_REGISTRATION: 'reject_registration',

  // Meetings
  REQUEST_MEETING: 'request_meeting',
  MANAGE_MEETINGS: 'manage_meetings',
  VIEW_OWN_MEETINGS: 'view_own_meetings',

  // CRM
  VIEW_CRM: 'view_crm',
  MANAGE_CRM: 'manage_crm',

  // MoU
  VIEW_MOU: 'view_mou',
  MANAGE_MOU: 'manage_mou',
  SIGN_MOU: 'sign_mou',

  // Pavilions
  VIEW_PAVILIONS: 'view_pavilions',
  MANAGE_PAVILIONS: 'manage_pavilions',

  // Events
  VIEW_EVENTS: 'view_events',
  MANAGE_EVENTS: 'manage_events',

  // Security
  SCAN_QR: 'scan_qr',
  VIEW_ATTENDANCE: 'view_attendance',
  MANUAL_CHECK_IN: 'manual_check_in',

  // Badges
  VIEW_BADGES: 'view_badges',
  PRINT_BADGE: 'print_badge',
  VERIFY_REGISTRATION: 'verify_registration',

  // Dashboards
  VIEW_CMO_DASHBOARD: 'view_cmo_dashboard',
  VIEW_MPIDC_DASHBOARD: 'view_mpidc_dashboard',
  VIEW_DEPT_DASHBOARD: 'view_dept_dashboard',

  // Admin
  MANAGE_ROLES: 'manage_roles',
  MANAGE_CONFIG: 'manage_config',
  MANAGE_NOTIFICATIONS: 'manage_notifications',
  VIEW_ADMIN: 'view_admin',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Permission matrix: which roles can do what */
const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.PUBLIC]: [
    PERMISSIONS.REGISTER,
  ],
  [ROLES.INVESTOR]: [
    PERMISSIONS.VIEW_OWN_REGISTRATION,
    PERMISSIONS.REQUEST_MEETING,
    PERMISSIONS.VIEW_OWN_MEETINGS,
    PERMISSIONS.VIEW_EVENTS,
  ],
  [ROLES.DELEGATE]: [
    PERMISSIONS.VIEW_OWN_REGISTRATION,
    PERMISSIONS.VIEW_OWN_MEETINGS,
    PERMISSIONS.VIEW_EVENTS,
  ],
  [ROLES.FOREIGN_INVESTOR]: [
    PERMISSIONS.VIEW_OWN_REGISTRATION,
    PERMISSIONS.REQUEST_MEETING,
    PERMISSIONS.VIEW_OWN_MEETINGS,
    PERMISSIONS.VIEW_EVENTS,
  ],
  [ROLES.STARTUP]: [
    PERMISSIONS.VIEW_OWN_REGISTRATION,
    PERMISSIONS.VIEW_OWN_MEETINGS,
    PERMISSIONS.VIEW_EVENTS,
  ],
  [ROLES.DEPARTMENT_VISITOR]: [
    PERMISSIONS.VIEW_OWN_REGISTRATION,
    PERMISSIONS.VIEW_EVENTS,
  ],
  [ROLES.DEPARTMENT_OFFICER]: [
    PERMISSIONS.VIEW_ALL_REGISTRATIONS,
    PERMISSIONS.APPROVE_REGISTRATION,
    PERMISSIONS.REJECT_REGISTRATION,
    PERMISSIONS.MANAGE_MEETINGS,
    PERMISSIONS.VIEW_MOU,
    PERMISSIONS.MANAGE_MOU,
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.VIEW_DEPT_DASHBOARD,
    PERMISSIONS.VIEW_EVENTS,
  ],
  [ROLES.REGISTRATION_DESK]: [
    PERMISSIONS.VIEW_ALL_REGISTRATIONS,
    PERMISSIONS.VERIFY_REGISTRATION,
    PERMISSIONS.VIEW_BADGES,
    PERMISSIONS.PRINT_BADGE,
    PERMISSIONS.MANUAL_CHECK_IN,
  ],
  [ROLES.RELATIONSHIP_MANAGER]: [
    PERMISSIONS.VIEW_ALL_REGISTRATIONS,
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.MANAGE_CRM,
    PERMISSIONS.MANAGE_MEETINGS,
    PERMISSIONS.VIEW_MOU,
    PERMISSIONS.MANAGE_MOU,
    PERMISSIONS.VIEW_EVENTS,
  ],
  [ROLES.PAVILION_MANAGER]: [
    PERMISSIONS.VIEW_PAVILIONS,
    PERMISSIONS.MANAGE_PAVILIONS,
    PERMISSIONS.VIEW_EVENTS,
  ],
  [ROLES.EVENT_ORGANIZER]: [
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.VIEW_PAVILIONS,
  ],
  [ROLES.SECURITY_STAFF]: [
    PERMISSIONS.SCAN_QR,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.MANUAL_CHECK_IN,
  ],
  [ROLES.MPIDC_ADMIN]: [
    PERMISSIONS.VIEW_ALL_REGISTRATIONS,
    PERMISSIONS.APPROVE_REGISTRATION,
    PERMISSIONS.REJECT_REGISTRATION,
    PERMISSIONS.MANAGE_MEETINGS,
    PERMISSIONS.VIEW_CRM,
    PERMISSIONS.MANAGE_CRM,
    PERMISSIONS.VIEW_MOU,
    PERMISSIONS.MANAGE_MOU,
    PERMISSIONS.VIEW_PAVILIONS,
    PERMISSIONS.MANAGE_PAVILIONS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.VIEW_BADGES,
    PERMISSIONS.PRINT_BADGE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_MPIDC_DASHBOARD,
    PERMISSIONS.VIEW_DEPT_DASHBOARD,
    PERMISSIONS.VIEW_ADMIN,
    PERMISSIONS.MANAGE_CONFIG,
  ],
  [ROLES.SUPER_ADMIN]: [
    // Super admin has all permissions
    ...Object.values(PERMISSIONS),
  ],
  [ROLES.CMO_OFFICIAL]: [
    PERMISSIONS.VIEW_CMO_DASHBOARD,
    PERMISSIONS.VIEW_MPIDC_DASHBOARD,
    PERMISSIONS.VIEW_EVENTS,
  ],
};

/** Check if a role has a specific permission */
export function hasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

/** Get all permissions for a role */
export function getPermissions(role: Role): Permission[] {
  return ROLE_PERMISSIONS[role] ?? [];
}

/** Route access mapping — which routes each role can access */
export const ROUTE_ACCESS: Record<string, Role[]> = {
  '/': [ROLES.PUBLIC, ...Object.values(ROLES)], // Landing page — everyone
  '/register': [ROLES.PUBLIC],
  '/status': [ROLES.PUBLIC, ROLES.INVESTOR, ROLES.DELEGATE, ROLES.FOREIGN_INVESTOR, ROLES.STARTUP, ROLES.DEPARTMENT_VISITOR],
  '/staff/approvals': [ROLES.DEPARTMENT_OFFICER, ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
  '/staff/badges': [ROLES.REGISTRATION_DESK, ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
  '/staff/meetings': [ROLES.DEPARTMENT_OFFICER, ROLES.RELATIONSHIP_MANAGER, ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
  '/staff/crm': [ROLES.RELATIONSHIP_MANAGER, ROLES.DEPARTMENT_OFFICER, ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
  '/staff/mou': [ROLES.DEPARTMENT_OFFICER, ROLES.RELATIONSHIP_MANAGER, ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
  '/staff/pavilions': [ROLES.PAVILION_MANAGER, ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
  '/staff/events': [ROLES.EVENT_ORGANIZER, ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
  '/staff/security': [ROLES.SECURITY_STAFF, ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
  '/staff/admin': [ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
  '/dashboards/cmo': [ROLES.CMO_OFFICIAL, ROLES.SUPER_ADMIN],
  '/dashboards/mpidc': [ROLES.MPIDC_ADMIN, ROLES.CMO_OFFICIAL, ROLES.SUPER_ADMIN],
  '/dashboards/department': [ROLES.DEPARTMENT_OFFICER, ROLES.MPIDC_ADMIN, ROLES.SUPER_ADMIN],
};
